# Generated by Django 2.2.1 on 2019-06-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190625_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='aubcategory',
            new_name='subcategory',
        ),
    ]
