# Generated by Django 2.2.1 on 2019-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190625_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('selection', models.CharField(default='', max_length=150)),
                ('phone', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
